service: amazon
provider:
    name: aws
    runtime: nodejs4.3
    stage: dev
    region: us-east-1
    memorySize: 512
functions:
    test-cgwkto: {handler: handler.test, events: [{http: {path: /test, method: post, private: false}}]}
